'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('MenuItems', [
      // North Indian (A2B Place)
      {
        name: 'Paneer Butter Masala',
        description: 'Creamy tomato-based gravy with soft paneer cubes.',
        price: 249.00,
        status: 'AVAILABLE',
        imageUrl: null,
        rating: 0.0,
        preparationTime: 20,
        isSpecial: false,
        discountPrice: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        BranchId: 3, // A2B Place
        CategoryId: 1, // North Indian
      },
      {
        name: 'Dal Makhani',
        description: 'Slow-cooked black lentils with butter and cream.',
        price: 199.00,
        status: 'AVAILABLE',
        imageUrl: null,
        rating: 0.0,
        preparationTime: 25,
        isSpecial: false,
        discountPrice: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        BranchId: 3,
        CategoryId: 1,
      },
      {
        name: 'Tandoori Roti',
        description: 'Traditional whole wheat roti cooked in a tandoor.',
        price: 20.00,
        status: 'AVAILABLE',
        imageUrl: null,
        rating: 0.0,
        preparationTime: 5,
        isSpecial: false,
        discountPrice: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        BranchId: 3,
        CategoryId: 1,
      },

      // South Indian (Sangeetha's)
      {
        name: 'Masala Dosa',
        description: 'Crispy dosa stuffed with spiced potato filling.',
        price: 99.00,
        status: 'AVAILABLE',
        imageUrl: null,
        rating: 0.0,
        preparationTime: 15,
        isSpecial: false,
        discountPrice: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        BranchId: 4, // Sangeetha's
        CategoryId: 2, // South Indian
      },
      {
        name: 'Idli Sambar',
        description: 'Steamed rice cakes served with sambar and chutneys.',
        price: 79.00,
        status: 'AVAILABLE',
        imageUrl: null,
        rating: 0.0,
        preparationTime: 10,
        isSpecial: false,
        discountPrice: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        BranchId: 4,
        CategoryId: 2,
      },
      {
        name: 'Medu Vada',
        description: 'Crispy deep-fried lentil fritters served with chutney.',
        price: 85.00,
        status: 'AVAILABLE',
        imageUrl: null,
        rating: 0.0,
        preparationTime: 10,
        isSpecial: false,
        discountPrice: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        BranchId: 4,
        CategoryId: 2,
      },

      // Street Food (Murari Sweets and chats)
      {
        name: 'Pani Puri',
        description: 'Crispy puris filled with spicy tangy water and mashed potatoes.',
        price: 60.00,
        status: 'AVAILABLE',
        imageUrl: null,
        rating: 0.0,
        preparationTime: 5,
        isSpecial: true,
        discountPrice: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        BranchId: 2, // Murari Sweets and chats
        CategoryId: 3, // Street Food
      },
      {
        name: 'Vada Pav',
        description: 'Spicy potato fritter served in a bun with chutney.',
        price: 40.00,
        status: 'AVAILABLE',
        imageUrl: null,
        rating: 0.0,
        preparationTime: 5,
        isSpecial: false,
        discountPrice: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        BranchId: 2,
        CategoryId: 3,
      },
      {
        name: 'Sev Puri',
        description: 'Crispy puris topped with potatoes, chutneys, and sev.',
        price: 50.00,
        status: 'AVAILABLE',
        imageUrl: null,
        rating: 0.0,
        preparationTime: 5,
        isSpecial: false,
        discountPrice: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        BranchId: 2,
        CategoryId: 3,
      },

      // Biryani (VRS Foods)
      {
        name: 'Hyderabadi Chicken Biryani',
        description: 'Fragrant basmati rice cooked with marinated chicken and spices.',
        price: 299.00,
        status: 'AVAILABLE',
        imageUrl: null,
        rating: 0.0,
        preparationTime: 30,
        isSpecial: true,
        discountPrice: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        BranchId: 1, // VRS Foods
        CategoryId: 4, // Biryani
      },
      {
        name: 'Veg Biryani',
        description: 'Basmati rice cooked with mixed vegetables and aromatic spices.',
        price: 199.00,
        status: 'AVAILABLE',
        imageUrl: null,
        rating: 0.0,
        preparationTime: 25,
        isSpecial: false,
        discountPrice: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        BranchId: 1,
        CategoryId: 4,
      },
      {
        name: 'Mutton Biryani',
        description: 'Spiced basmati rice cooked with Tender Mutton and herbs.',
        price: 229.00,
        status: 'AVAILABLE',
        imageUrl: null,
        rating: 0.0,
        preparationTime: 20,
        isSpecial: false,
        discountPrice: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        BranchId: 1,
        CategoryId: 4,
      },

      // Fast Foods (KFC)
      {
        name: 'Crispy Fried Chicken',
        description: 'Crispy fried chicken served with a tangy sauce.',
        price: 99.00,
        status: 'AVAILABLE',
        imageUrl: null,
        rating: 0.0,
        preparationTime: 0,
        isSpecial: true,
        discountPrice: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        BranchId: 5, // KFC
        CategoryId: 7, // Fast Foods
      },
      {
        name: 'Gulab Jamun',
        description: 'Deep-fried dough balls soaked in sugar syrup.',
        price: 80.00,
        status: 'AVAILABLE',
        imageUrl: null,
        rating: 0.0,
        preparationTime: 0,
        isSpecial: false,
        discountPrice: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        BranchId: 5,
        CategoryId: 6,
      },
      {
        name: 'Mishti Doi',
        description: 'Sweetened fermented yogurt with a creamy texture.',
        price: 100.00,
        status: 'AVAILABLE',
        imageUrl: null,
        rating: 0.0,
        preparationTime: 0,
        isSpecial: false,
        discountPrice: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        BranchId: 5,
        CategoryId: 6,
      },{
        name: 'Mixed Chicken fried Rice',
        description: 'Fried rice served with a variety of chicken and vegetables.',
        price: 89.00,
        status: 'AVAILABLE',
        imageUrl: null,
        rating: 0.0,
        preparationTime: 0,
        isSpecial: false,
        discountPrice: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        BranchId: 1,
        CategoryId: 5,
      }
    ], {});
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('MenuItems', null, {});
  }
};
